KeyStore: Add getApplicationContext method required for Asus Devices
- Since Google migrated keystore to v2 they removed getApplicationContext which is required by Asus Flip Camera MotorService app.
- This fixes following issue

10-14 08:53:32.136  2491  2491 E AndroidRuntime: FATAL EXCEPTION: main
10-14 08:53:32.136  2491  2491 E AndroidRuntime: Process: com.asus.motorservice, PID: 2491
10-14 08:53:32.136  2491  2491 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getApplicationContext()Landroid/content/Context; in class Landroid/security/KeyStore; or its super classes (declaration of 'android.security.KeyStore' appears in /system/framework/framework.jar!classes2.dex)
10-14 08:53:32.136  2491  2491 E AndroidRuntime:   at com.asus.motorservice.t.<init>(Unknown Source:29)

Change-Id: I9c95000a8f3d26022bad4a5db85eb8de48f8aa49
Signed-off-by: Jackeagle <jackeagle102@gmail.com>